//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Front.WebServiceLista {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.org/", ConfigurationName="WebServiceLista.WsListaSoap")]
    public interface WsListaSoap {
        
        // CODEGEN: Generating message contract since element name GetListaResult from namespace http://webService.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webService.org/GetLista", ReplyAction="*")]
        WebApp.Front.WebServiceLista.GetListaResponse GetLista(WebApp.Front.WebServiceLista.GetListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService.org/GetLista", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.Front.WebServiceLista.GetListaResponse> GetListaAsync(WebApp.Front.WebServiceLista.GetListaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLista", Namespace="http://webService.org/", Order=0)]
        public WebApp.Front.WebServiceLista.GetListaRequestBody Body;
        
        public GetListaRequest() {
        }
        
        public GetListaRequest(WebApp.Front.WebServiceLista.GetListaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListaRequestBody {
        
        public GetListaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListaResponse", Namespace="http://webService.org/", Order=0)]
        public WebApp.Front.WebServiceLista.GetListaResponseBody Body;
        
        public GetListaResponse() {
        }
        
        public GetListaResponse(WebApp.Front.WebServiceLista.GetListaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webService.org/")]
    public partial class GetListaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListaResult;
        
        public GetListaResponseBody() {
        }
        
        public GetListaResponseBody(string GetListaResult) {
            this.GetListaResult = GetListaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsListaSoapChannel : WebApp.Front.WebServiceLista.WsListaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsListaSoapClient : System.ServiceModel.ClientBase<WebApp.Front.WebServiceLista.WsListaSoap>, WebApp.Front.WebServiceLista.WsListaSoap {
        
        public WsListaSoapClient() {
        }
        
        public WsListaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsListaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsListaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsListaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.Front.WebServiceLista.GetListaResponse WebApp.Front.WebServiceLista.WsListaSoap.GetLista(WebApp.Front.WebServiceLista.GetListaRequest request) {
            return base.Channel.GetLista(request);
        }
        
        public string GetLista() {
            WebApp.Front.WebServiceLista.GetListaRequest inValue = new WebApp.Front.WebServiceLista.GetListaRequest();
            inValue.Body = new WebApp.Front.WebServiceLista.GetListaRequestBody();
            WebApp.Front.WebServiceLista.GetListaResponse retVal = ((WebApp.Front.WebServiceLista.WsListaSoap)(this)).GetLista(inValue);
            return retVal.Body.GetListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.Front.WebServiceLista.GetListaResponse> WebApp.Front.WebServiceLista.WsListaSoap.GetListaAsync(WebApp.Front.WebServiceLista.GetListaRequest request) {
            return base.Channel.GetListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.Front.WebServiceLista.GetListaResponse> GetListaAsync() {
            WebApp.Front.WebServiceLista.GetListaRequest inValue = new WebApp.Front.WebServiceLista.GetListaRequest();
            inValue.Body = new WebApp.Front.WebServiceLista.GetListaRequestBody();
            return ((WebApp.Front.WebServiceLista.WsListaSoap)(this)).GetListaAsync(inValue);
        }
    }
}
